### ISSUE TITLE
ROS 2 rework roadmap

### ISSUE THREAD

**Issue by jlblancoc** [mrpt-ros-pkg/mrpt_navigation#135]
List of goals for the ROS 2 transition. It will not only be a port of old ROS 1 packages, but a refactoring with the learned experience:

Each package subdirectory should have a `README.md` with all the relevant documentation: parameters, topics, etc.

- ~~`mrpt_local_obstacles`~~  => `mrpt_pointcloud_pipeline`: Sensor inputs to basic / decimated point cloud.
  - [x] Port to ROS 2
  - [x] Check and document what sensor types are supported. Check if #121 is already handled.
  - [ ] Write tests

- `mrpt_msgs_bridge`: C++ library to convert msgs to C++ classes, for those messages defined in `mrpt_msgs` and hence not possible to include into `mrpt::ros2bridge`:
  - [x] Port to ROS 2
  - [ ] Write tests

- `mrpt_map`: Read maps from file and publishes them.
  - [x] Port existing ROS1 version to ROS 2
  - [ ] Offer a ROS service to dynamically load/reload the map.
  - [ ] Write tests
  - [x] Improve so it can read other map types: pointclouds, octomaps, etc.

- Old ROS 1 `mrpt_localization` should be renamed ==> `mrpt_pf_localization`: Uses particle filter methods to localize
  - [x] Port old ROS 1 version to ROS 2
  - [x] Rename package in all places where it's used: `mrpt_localization` ==> `mrpt_pf_localization`
  - [ ] Write tests
  - [ ] Expose and document the different options of particle filter algorithms that exist.
  - [ ] Add a service or topic to allow switching the map (TBD). cc: #123
  - [ ] Expose a localization quality metric. cc #122
  - [ ] Write demos of localization using as map:
      - [x] Occupancy grid map.
      - [ ] Point cloud.

- Create new package `mrpt_opt_localization`: Uses optimization-based localization:
  - [x] Superseded by MOLA. 

- `mrpt_rawlog`: Nodes to record .rawlog and play .rawlog.
  - [x] Port existing ROS1 version to ROS 2. Probably reuse code from mrpt/rosbag2rawlog app.
  - [x] Check if #96 is still an issue
  - [x] Remove rawlog_play and add a demo/docs for preferred usage of MOLA ROS2 bridge.
  - [ ] Write tests

- `mrpt_reactivenav2d`: The pure reactive method with a 2D robot shape for planar motion.
  - [x] Port existing ROS1 version to ROS 2. Probably reuse code from mrpt/rosbag2rawlog app.
  - [ ] Write tests/demos

- `mrpt_tutorials`: Probably, rename to ==> `mrpt_navigation_tutorials`
  - [x] Port existing ROS1 version to ROS 2.

- `mrpt_tps_astar_planner`: New A* planner

Other tasks:
- [x] Add proper CI and branch rules. Use these Docker images: https://hub.docker.com/r/osrf/ros/tags
- [X] When all/most of the above are done, switch the main branch of this repo to `ros2` and mark `ros1` as obsolete.
- [x] Make the first ROS 2 release to all active distros.

**Comment by jlblancoc** [comment]
cc: @SRai22 Here we are... :-)

**Comment by SRai22** [comment]
Check and document what sensor types are supported. Check if https://github.com/mrpt-ros-pkg/mrpt_navigation/issues/121 is already handled. 

Currently we are handling both inputs, sensor_msgs::msg::LaserScan and  sensor_msgs::msg::PointCloud2 in mrpt_local_obstacles.

**Comment by jlblancoc** [comment]
CI is now setup and working, and commits to the main "ros2" branch should now go thru PRs that pass the tests! 
Latest one is #139 , still WIP due to a large refactoring work in progress, will merge when the CI tests pass, that will mean it builds ok on all ROS2 distros :smile:

**Comment by KatoROSTeam** [comment]
When can we Expect the mrpt_pf_localization

**Comment by jlblancoc** [comment]
It's for sure one of my top priorities... but I'm almost done finishing first a brand new Lidar-SLAM package that will generate maps for these localization packages, so this one is enqueued at present... 

I definitively want both works to be out by December... 

PS: I'll post updates on my LinkedIn profile, as usual.

**Comment by jlblancoc** [comment]
Finally back to this project...
These updated READMEs explain the new way metric maps are to be handled: 
- https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_map
- https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_pf_localization

(More news soon...)

**Comment by KatoROSTeam** [comment]
Great to see you back here! Hoping mrpt_pf_localization will release on this December. @jlblancoc

**Comment by jlblancoc** [comment]
Hi @KatoROSTeam : 
Officially releasing so users can install it via "apt install..." will take some more weeks, since there is a long queue of pending tasks to publish all the related packages (mola_common, mp2p_icp, etc.) and the ROS infrastructure guys are not moving things forwards these days (they also have the right to rest in holidays!). 

But you can test it if built locally. Basic pf-localization, with a 2D gridmap and a 2D lidar, is already working ok for ROS2 and there is a demo ready to test: https://github.com/mrpt-ros-pkg/mrpt_navigation/tree/ros2/mrpt_pf_localization#demos
with a video of the result here: https://mrpt.github.io/videos/pf_localization_demo_2dgrid_mvsim.mp4

To build locally, prepare a ROS2 workspace as usual, and clone in its `src`:
- https://github.com/MOLAorg/mola_common
- https://github.com/MOLAorg/mp2p_icp
- The latest MRPT2 (>=2.11.5) , must be also built from sources, unless you have ROS iron, since it's already published there: https://github.com/mrpt-ros-pkg/ros-build-farm-statuses
- Then, this repo, of course: https://github.com/mrpt-ros-pkg/mrpt_navigation/
- MVSim is required for the demo, but you can install it with `sudo apt install ros-${ROS_DISTRO}-mvsim` 

Hope it helps.

**Comment by KatoROSTeam** [comment]
Hi @jlblancoc , In mrpt_pf_localization_node.cpp, i can find that lot of functions that required to localize on a given map are stopped from running using the #if 0 like below example,
```void PFLocalizationNode::odometryForCallback(
	CObservationOdometry::Ptr& _odometry,
	const std_msgs::msg::Header& _msg_header)
{
#if 0
	std::string base_frame_id = param()->base_frame_id;
	std::string odom_frame_id = param()->odom_frame_id;
	mrpt::poses::CPose3D poseOdom;
	if (this->waitForTransform(
			poseOdom, odom_frame_id, base_frame_id, _msg_header.stamp,
			ros::Duration(1.0)))
	{
		_odometry = CObservationOdometry::Create();
		_odometry->sensorLabel = odom_frame_id;
		_odometry->hasEncodersInfo = false;
		_odometry->hasVelocities = false;
		_odometry->odometry.x() = poseOdom.x();
		_odometry->odometry.y() = poseOdom.y();
		_odometry->odometry.phi() = poseOdom.yaw();
	}
#endif
}
```


Also the localization launch also not providing map frame as well. How to fix this

**Comment by jlblancoc** [comment]
@KatoROSTeam  This package is now working on a daily basis on our robots, so you could use it now. 

@SRai22 I started importing our TPS A* planner into a new branch, and will try to port it to ROS 2 asap ;-)

**Comment by logesh-gtx** [comment]
Will there be a localization package based on Landmark Maps in Mrpt ? (Landmarks -- such as QR codes )
or is there a way to generate landmark maps with Mrpt and how to use it for SLAM / Localization

**Comment by jlblancoc** [comment]
@logesh-gtx It has been a long pending to-do item... 

MRPT C++ libraries do implement EKF-SLAM for 3D motion and 3D landmarks. It was exposed as ROS1 package [mrpt_slam](https://github.com/mrpt-ros-pkg/mrpt_slam), but it was never ported to ROS2 for lack of bandwidth from my side and lack of volunteers :-)

**Comment by logesh-gtx** [comment]
I have thinking about integrating reflector Tags as landmarks in mrpt slam, but i dont have a concrete base on where i should start any suggestions or any documents available on MRPT? slam engine and how does it work with ros2 

from looking into the header files of mrpt i can find there is a **<mrpt/obs/CObservationReflectivity.h>** Reflectivity as an observation source is it the same as reflective tags or something else

**Comment by jlblancoc** [comment]
One way would be to start: 
- Copying this directory [mrpt_ekf_slam_3d](https://github.com/mrpt-ros-pkg/mrpt_slam/tree/ros1/mrpt_ekf_slam_3d) into a brand new repo, eg. named `mrpt_ekf_slam_3d`, now with the aim of being the new ros2 repo.
- Upgrade all the ROS1-related stuff to ROS2. ChatGPT is a good help here...
- Once done, the visual tags/markers should be converted (using its own independent package) into [mrpt_msgs/ObservationRangeBearing](https://github.com/mrpt-ros-pkg/mrpt_msgs/blob/master/msg-ros1/ObservationRangeBearing.msg). That message is already defined and working in ROS1 & ROS2 in the package `mrpt_msgs`

**Comment by jlblancoc** [comment]
PS: I realized you never actually asked for ROS2... if you still work in ROS1, the only missing piece is the third bullet above.
